name: Docker secrets workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GPG passphrase
        env:
          GPG_PASSPHRASE: ${{ secrets.GPP_DEC_KEY }}
        run: |
          echo "Passphrase set."

      - name: Decrypt Secrets
        run: |
          ./gpg_crypt.sh decrypt
        env:
          GPG_PASSPHRASE: ${{ secrets.GPP_DEC_KEY }}

      - name: Deploy to docker secrets
        run: |
          ./secrets.sh
      
      - name: Delete decrypted file
        run: |
          rm secrets
