global:
  checkNewVersion: false
  sendAnonymousUsage: false

# -- (Optional) Change Log Level and Format here...
#     - loglevels [DEBUG, INFO, WARNING, ERROR, CRITICAL]
#     - format [common, json, logfmt]
# log:
#  level: ERROR
#  format: common
#  filePath: /var/log/traefik/traefik.log

# -- (Optional) Enable Accesslog and change Format here...
#     - format [common, json, logfmt]
# accesslog:
#   format: common
#   filePath: /var/log/traefik/access.log

# -- (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
  disableDashboardAd: true
  # insecure: true

# -- Change EntryPoints here...
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "0.0.0.0/0"
    # -- (Optional) Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http2:
      maxConcurrentStreams: 1000
    forwardedHeaders:
      trustedIPs:
        - "0.0.0.0/0"
    transport:
      respondingTimeouts:
        readTimeout: 300
        writeTimeout: 300
        idleTimeout: 300
      keepAliveMaxRequests: 42
      keepAliveMaxTime: 300s
  bolt:
    address: ":7687"

  # -- (Optional) Add custom Entrypoint
  # custom:
  #   address: :8080

# -- Configure your CertificateResolver here...
certificatesResolvers:
  staging:
    acme:
      email: cris.tarpin@splitsecondresearch.com
      storage: /ssl-certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      # (Optional) Remove this section, when using DNS Challenge
      httpChallenge:
        entryPoint: web
  production:
    acme:
      email: cris.tarpin@splitsecondresearch.com
      storage: /ssl-certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      # (Optional) Remove this section, when using DNS Challenge
      httpChallenge:
        entryPoint: web

# -- (Optional) Disable TLS Cert verification check
# serversTransport:
#   insecureSkipVerify: true

# -- (Optional) Overwrite Default Certificates
# tls:
#   certificates:
#     - certFile: /ssl-certs/traefik.local.crt
#       keyFile: /ssl-certs/traefik.local.key
#     - certFile: /ssl-certs/pma.local.crt
#       keyFile: /ssl-certs/pma.local.key
#     - certFile: /ssl-certs/fluent.local.crt
#       keyFile: /ssl-certs/fluent.local.key
#     - certFile: /ssl-certs/ws.local.crt
#       keyFile: /ssl-certs/ws.local.key
#     - certFile: /ssl-certs/wordpress.crt
#       keyFile: /ssl-certs/wordpress.key
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# -- (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12

providers:
  swarm:
    # -- (Optional) Enable this, if you want to expose all containers automatically
    #exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  # docker: 
  #   exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
  
    