services:
  pma:
    image: docker.io/library/phpmyadmin:latest
    networks:
      - web2
    environment:
      - PMA_ARBITRARY=1
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pma.rule=Host(`pma.connoisseur-suite.com`)"
        - "traefik.http.routers.pma.entrypoints=websecure"
        - "traefik.http.routers.pma.tls=true"
        - "traefik.http.routers.pma.tls.certresolver=production"
        - "traefik.http.services.pma.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == worker

networks:
  web2:
    external: true