services:
  traefik:
    image: traefik:v3.6
    networks:
      - web
    ports:
      - protocol: tcp
        published: 80
        target: 80
        mode: host
      - protocol: tcp
        published: 443
        target: 443
        mode: host
      - protocol: tcp
        published: 7687
        target: 7687
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/headers.yaml:/etc/traefik/headers.yaml:ro
      - traefik-ssl-certs:/ssl-certs
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy: 
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.connoisseur-suite.co.uk`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.middlewares=auth"
        # to create user run commnd `echo $(htpasswd -nB user) | sed -e s/\\$/\\$\\$/g` ssr-admin 98_ujah£41+1334
        - "traefik.http.middlewares.auth.basicauth.users=ssr-admin:$$2y$$05$$DZ1wvrVWmKJH3kT3eM7GQ.jBcF918sp7eje1uAqdXoK0uFMy7Ego2"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=production"
      placement:
        constraints:
          - node.role == manager

  mariadb:
    image: docker.io/library/mariadb:11.2
    networks:
      - web
    environment:
      - MARIADB_ROOT_PASSWORD=2pegA8eZ6BR2P1ewror
      - MARIADB_DATABASE=laravel
      - MARIADB_USER=local
      - MARIADB_PASSWORD=2pegA8eZ6BR2P1ewror
    volumes:
      - sql_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - node.role == manager
  
  pma:
    image: docker.io/library/phpmyadmin:5.2.1-apache
    networks:
      - web
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD_FILE=/run/secrets/fluent_db_password
      - PMA_CONFIG_SERVERS_1_AUTH_TYPE=config
    secrets:
      - fluent_db_password
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pma.rule=Host(`pma.connoisseur-suite.co.uk`)"
        - "traefik.http.routers.pma.entrypoints=websecure"
        - "traefik.http.routers.pma.tls=true"
        - "traefik.http.routers.pma.tls.certresolver=production"
        - "traefik.http.services.pma.loadbalancer.server.port=80"
        - "traefik.http.routers.pma.middlewares=auth"
        # to create user run commnd `echo $(htpasswd -nB user) | sed -e s/\\$/\\$\\$/g` ssr-admin 98_ujah£41+1334
        - "traefik.http.middlewares.auth.basicauth.users=ssr-admin:$$2y$$05$$DZ1wvrVWmKJH3kT3eM7GQ.jBcF918sp7eje1uAqdXoK0uFMy7Ego2"
      placement:
        constraints:
          - node.role == manager
    
networks:
  web:
    external: true

volumes:
  traefik-ssl-certs:
    driver: local
  sql_data:
    driver: local

secrets:
  fluent_db_password:
    external: true