# kubectl apply -f databases/ui/do/mongo_ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-ingress
  namespace: databases
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingressClassName: "traefik"
spec:
  tls:
  - hosts:
    - mongo.jellibean.co.uk
    secretName: mongo-tls
  rules:
    - host: mongo.jellibean.co.uk
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mongo-express
                port:
                  number: 8081